// <auto-generated />
using System;
using MiAreaVol.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiAreaVol.Migrations
{
    [DbContext(typeof(MiAreaVolContext))]
    [Migration("20250622223847_InitialCreateFixed")]
    partial class InitialCreateFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MiAreaVol.Models.CalculoArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Altura")
                        .HasColumnType("double");

                    b.Property<double?>("Ancho")
                        .HasColumnType("double");

                    b.Property<double?>("Base")
                        .HasColumnType("double");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Lado")
                        .HasColumnType("double");

                    b.Property<double?>("Largo")
                        .HasColumnType("double");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("Radio")
                        .HasColumnType("double");

                    b.Property<double>("Resultado")
                        .HasPrecision(18, 6)
                        .HasColumnType("double");

                    b.Property<string>("TipoFigura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CalculosArea", (string)null);
                });

            modelBuilder.Entity("MiAreaVol.Models.CalculoVolumen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Altura")
                        .HasColumnType("double");

                    b.Property<double?>("Ancho")
                        .HasColumnType("double");

                    b.Property<double?>("Base")
                        .HasColumnType("double");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Lado")
                        .HasColumnType("double");

                    b.Property<double?>("Largo")
                        .HasColumnType("double");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("Profundidad")
                        .HasColumnType("double");

                    b.Property<double?>("Radio")
                        .HasColumnType("double");

                    b.Property<double>("Resultado")
                        .HasPrecision(18, 6)
                        .HasColumnType("double");

                    b.Property<string>("TipoFigura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CalculosVolumen", (string)null);
                });

            modelBuilder.Entity("MiAreaVol.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
